deploy:
  on:
    condition: "$TOXENV == py27"
    repo: danrue/gluster_stats
    tags: true
  distributions: sdist bdist_wheel
  password:
    secure: Kxqwflxc68mqYEx+8QX2TRqlJxKZDC24KcpLiEr61jEMFOQz4J+39r+z+/UhtHI43fN+bwXUdvF9aTYvl6xTd2xDovlWr92tI9mmi9MX27VWnNRL98vmdUXigfdZYVPcUYIIZoFHgnUQMH8AMciFkYZM7To5cUhSihdJOYP7ldvqmnzvY0qO+QAlb2kV0Vhn0XsblneDcdotoCKuDxQRnNPb726dmrrxbzkwiu1NSs5PyshAI4rnAo6wEB7QlexYtqPU2t7/roYSCTYW6sXkwnU5H1TGuz9ZBVTj3yLkErnAtFkw+CGXx7Lx8ZgRXqd7R5AcX4Bw6xjgRfUHNeDSBWy/hCD4LLOQy0iDtKUxTHOOQVClID7JL1Gij/Oj8LKzvICKyuw5Ffmi8qWVCB5A/NCXVDa/GQUYP6u8EcbffIQ0x+Fb0vB/SRYoXDCkPOsF9MCeHbuhav0OKj/f9C5CChpFrtcmudmorNkn9p/HFxaRYO/cocZeqTKkydmLBYmi6Jt/ASdMz5DHcEGHNTgjF9o7d1fV0p96nUgsFL0HoThO8jPdrD4IEoudbMPa46JsJfs6mUxBUAp2tkFla3WgwEwvlyFuojzQvPohK5jBfwzMTq1ozDW3qbmkXG6PXAkCBS9UhSHGip4oyL0or3JVk4qCsp7kDCmWzb0fXUDyyHE=
  provider: pypi
  user: danrue
python: 3.5
env:
- TOXENV=py35
- TOXENV=py34
- TOXENV=py33
- TOXENV=py27
- TOXENV=py26
- TOXENV=pypy
install: pip install -U tox
language: python
script: tox
